# Generated by Django 5.2.8 on 2026-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_experience_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Noida, India', max_length=255, null=True),
        ),
    ]
