# Generated by Django 5.2.8 on 2026-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_personaldata_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
