# Generated by Django 5.2.8 on 2026-03-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_personaldata_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='core_tech_stack',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
