# Generated by Django 5.2.8 on 2026-03-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_personaldata_core_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='current_focus',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='primary_deliverable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='working_style',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
