# Generated by Django 5.2.8 on 2026-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_personaldata_current_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('main', 'Main Portfolio'), ('freelance', 'Freelance Portfolio')], default='main', help_text='Select where this project should be displayed', max_length=20),
        ),
    ]
